### Config Deployment ( use replicaset for blue/green deployment spinnaker)###
apiVersion: v1
kind: Service
metadata:
  name: $GKE_DEPLOYMENT_NAME
  labels:
    app: $GKE_DEPLOYMENT_NAME
spec:
  selector:
    app: $GKE_DEPLOYMENT_NAME
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  #name: stag-cms
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service $GKE_DEPLOYMENT_NAME"]'
  labels:
    tier: $GKE_DEPLOYMENT_NAME
  name: $GKE_DEPLOYMENT_NAME
spec:
  replicas: $GKE_POD_MINIMUM_REPLICAS
  selector:
    matchLabels:
      tier: $GKE_DEPLOYMENT_NAME
  template:
    metadata:
      labels:
        tier: $GKE_DEPLOYMENT_NAME
        #env: staging
    spec:
      containers:
      - name: $GKE_DEPLOYMENT_NAME
        image: "$GKE_REGISTRY_REGION/$GKE_PROJECT_ID/$GKE_DEPLOYMENT_NAME:$GKE_BRANCH"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
            limits:
               cpu: "$GKE_POD_CPU"
               memory: "$GKE_POD_MEMORY"
        # health checks self healing check port 8080 response 200,
        # if containers error (400-500) kubernetes restart the pod
        # NOTE: this config health check will use by ingress
        readinessProbe:
          httpGet:
            path: $GKE_POD_HEALTHCHECK
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 6
          periodSeconds: 10
        livenessProbe:
           httpGet:
             path: $GKE_POD_HEALTHCHECK
             port: 8080
           initialDelaySeconds: 15
           timeoutSeconds: 6
           periodSeconds: 10
---
### Config Autoscale ###
# NOTE: Config Autoscale pods deployment
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: $GKE_DEPLOYMENT_NAME
#  namespace: default
spec:
  maxReplicas: 25
  minReplicas: $GKE_POD_MINIMUM_REPLICAS
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: ReplicaSet
    name: $GKE_DEPLOYMENT_NAME
  targetCPUUtilizationPercentage: 70
